# Generated by Django 2.0.5 on 2018-07-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cdata', models.CharField(max_length=500)),
                ('ctime', models.DateTimeField()),
                ('child_comment', models.ForeignKey(blank=True, null=True, on_delete=True, to='mainapp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Community_list',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=20)),
                ('rfield', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pdata', models.CharField(max_length=3000, null=True)),
                ('ptime', models.DateTimeField(auto_now=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_photo_path)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Community_list')),
            ],
        ),
        migrations.CreateModel(
            name='User_registered_comunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Community_list')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='pcid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.User_registered_comunities'),
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
